import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import {QrScanner} from '@yudiel/react-qr-scanner';
import { useEffect, useState } from 'react'
import axios from 'axios';

export default function Home() {

  const [saved, setSaved] = useState(false);
  const [verified, setVerified] = useState(false);

  return (
    <>
      <Head>
        <title>QR Code Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QrScanner onDecode={(result) => {
        if (!saved && result.startsWith('ey') && confirm('Vuoi salvare questa credenziale sul telefono?')) {
          setSaved(true);
          localStorage.setItem('jwt', result);
        }
        else if (result.startsWith('http') && !verified) {
          alert('!');
          setVerified(true);
          axios.post(result, {
            jwt: localStorage.getItem('jwt')
          });
          alert('Verified! Check out on the other service');
        }
      }} onError={function (error: Error): void {}} />
    </>
  )
}
